[package]
name = "clave"
version = "0.4.1"
edition = "2021"
description = "Midi click-track generator"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
midly = { version = "0" }
regex = { version = "1" }